#server:
#  port: 9080
mybatis:
#  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.example.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    可以打印mysql语句
    map-underscore-to-camel-case: true
#    帮助我们使用驼峰，java里面用驼峰表示属性

spring:
  application:
    name: user-server
  config:
    import: nacos:user-server.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.147.1:8848
      config:
        server-addr: 192.168.147.1:8848
        file-extension: yaml
        shared-configs: #共享配置应放在spring.cloud.nacos.config下
          - data-id: database.yaml
            group: DEFAULT_GROUP
            refresh: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    # 确保H2使用MySQL兼容模式
#    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tododb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "040906"
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false # 开发环境关闭缓存，生产环境应设为 true
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.springframework: DEBUG
    org.springframework.jdbc: TRACE
    com.zaxxer.hikari: DEBUG
#app:
#  base-url: https://your-app.com

