#server:
#  port: 9084

spring:
  application:
    name: audit-server
  config:
    import: nacos:audit-server.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.147.1:8848
      config:
        server-addr: 192.168.147.1:8848
        file-extension: yaml