#server:
#  port: 9082

spring:
  application:
    name: admin-service
  config:
    import: nacos:admin-service.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.147.1:8848
      config:
        server-addr: 192.168.147.1:8848
        file-extension: yaml