name: Build and Deploy to K3s

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: docker.io/${{ secrets.DOCKER_USERNAME }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push User Server
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./user-server/Dockerfile
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/user-server:latest

    - name: Build and Push Todo Server
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./todo-server/Dockerfile
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/todo-server:latest

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup SSH Tunnel
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.K3S_HOST }} >> ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no -N -L 6443:localhost:6443 ${{ secrets.K3S_USER }}@${{ secrets.K3S_HOST }} &
        sleep 5

    - name: Deploy to K3s
      uses: azure/k8s-deploy@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        manifests: |
          k8s/user-server-deployment.yaml
          k8s/todo-server-deployment.yaml
        images: |
          ${{ env.DOCKER_REGISTRY }}/user-server:latest
          ${{ env.DOCKER_REGISTRY }}/todo-server:latest 